# Generated by Django 3.2.16 on 2023-04-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djauth', '0002_announcement'),
        ('djauth', '0006_tests'),
    ]

    operations = [
    ]
