# Generated by Django 3.2.16 on 2023-05-15 01:36

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('djauth', '0007_merge_0002_announcement_0006_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number',
            field=models.IntegerField(default=1, validators=[MinValueValidator(1, message='Number of questions must be 1 or greater.'),]),
        ),
    ]
