# Generated by Django 3.2.16 on 2023-05-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djauth', '0009_auto_20230521_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='Exams', to='djauth.QuesModel'),
        ),
    ]
