# Generated by Django 3.2.16 on 2023-05-21 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djauth', '0010_auto_20230521_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('num_questions', models.PositiveIntegerField()),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='passwd',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classname',
            new_name='scores',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gradelvl',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.CharField(default='ACT', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='ACT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PDFTestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('pdftest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djauth.pdftest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
