# Generated by Django 4.1.5 on 2023-05-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djauth', '0003_profile'),
        ('djauth', '0012_remove_student_classes_remove_student_scores'),
    ]

    operations = [
    ]
