# Generated by Django 4.1.5 on 2023-05-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djauth', '0013_merge_20230522_0429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
