# Generated by Django 4.1.5 on 2023-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djauth', '0014_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInquirie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inqteacherfirstname', models.CharField(default='#', max_length=50)),
                ('inqteacherlastname', models.CharField(default='#', max_length=50)),
                ('inqteacheremail', models.EmailField(default='#', max_length=200)),
                ('inqteachermessage', models.CharField(default='#', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='PDFTestSubmission',
        ),
    ]
