# Generated by Django 3.2.16 on 2023-05-31 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djauth', '0015_teacherinquirie_delete_pdftestsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='test',
            name='number',
        ),
    ]
