# Generated by Django 4.1.7 on 2023-06-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djauth', '0016_auto_20230531_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
